### ISSUE TITLE
Problema utilizando Interfaz

### ISSUE THREAD

**Issue by mbburstein** [eamontoyaa/pyCSS#1]
Hola,

Estoy intentando correr el programa pyCSS.py, y cuando ingreso los valores en el cuadro con la interfaz me arroja diversos errores:

- return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

No sé, si existen algunas restricciones para los valores de la Geometría del talud, que no me permite correr bien el código.

Muchas gracias,
Marcelo

**Comment by eamontoyaa** [comment]
Buenas tardes Marcelo.

Le pido amablemente el favor de que me suministre los valores de entrada que le están generando ese error para poder revisarlo y con ello estaremos realizando los respectivos ajustes.

Saludos cordiales,
Exneyder Montoya

**Comment by mbburstein** [comment]
Aquí va una imagen que he intentado probar. Muchas gracias por la pronta respuesta.


![imagen_1](https://cloud.githubusercontent.com/assets/15880966/23374554/8ca372f6-fd03-11e6-99ce-9ec8f4fd6ab5.png)

**Comment by eamontoyaa** [comment]
Marcelo, en la imagen observo que hace falta introducir los parámetros del suelo. Yo puse unos aleatorios para verificar y el análisis fue ejecutado sin problema. Adjunto el pantallazo, y los archivos obtenidos con el análisis. 

Por favor intente nuevamente y me comenta si el problema persiste que estaré atento. 

Saludos cordiales!

![testmarcelo](https://cloud.githubusercontent.com/assets/17820465/23374983/9f44728e-fcf4-11e6-9853-fa34408495f4.png)
![test_1](https://cloud.githubusercontent.com/assets/17820465/23374971/907b7c66-fcf4-11e6-998b-7511d014ff52.png)
[test_1.txt](https://github.com/eamontoyaa/pyCSS/files/804682/test_1.txt)

**Comment by mbburstein** [comment]
Era eso el problema, ya está solucionado, muchas gracias! 

Aprovechando quería comentarte otra consulta, a veces me arrojaba un error sobre la pendiente, diciendo que las variables x e y no podían ser menos que 3, a qué se refiere eso?

**Comment by eamontoyaa** [comment]
Marcelo, según le entiendo, ese aviso no le sale siempre, sino ocasionalmente; le pediré el favor de cuando le vuelva a aparecer, me comparta nuevamente los datos de entrada para revisarlo.

Gracias por las observaciones!

Saludos cordiales,
EM

**Comment by mbburstein** [comment]
Hola Exneyder,

Aparentemente me surgió otro error, pero puede deberse a que cambié de sistema operativo. Ahora me puse a probar el programa en Windows 10 (antes estaba en Ubuntu) y me está surgiendo el siguiente problema (utilizando los mismos valores de la foto que está arriba):
![cmd](https://cloud.githubusercontent.com/assets/15880966/23412251/bfb8f5f2-fdb3-11e6-95f3-526c2b2d5243.png)

Sabes a qué puede deberse?

Muchas gracias. Saludos,
MB

**Comment by eamontoyaa** [comment]
Buen día Marcelo!

Recién hice la prueba en Windows7 con los mismos valores del ejemplo que le adjunté anteriormente y no hubo problema, para verificar ello le adjunto los archivos obtenidos para que lo observe.

¿Al ejecutar el módulo pyCSS (el que invoca la interfaz gráfica) le genera ese error y no sale la ventada de la interfaz o si le abre la interfaz y al ejecutarlo le genera el error? Si ni siquiera le abre la ventana, el error está probablemente en el módulo de tkinter que tenga instalado, por lo que le recomiendo reinstalarlo o actualizarlo. Si le genera complicaciones la instalación/actualización, utilice el gestor de paquetes llamado "Conda" de la distribución de Python llamada "Anaconda" (esto se recomienda en el manual)

Quedo atento.
Saludos, EM.

![testmarceloonwindows7](https://cloud.githubusercontent.com/assets/17820465/23463709/844b6b0a-fe60-11e6-8313-346fb208335c.PNG)
![test_1](https://cloud.githubusercontent.com/assets/17820465/23463737/9c9e51ae-fe60-11e6-8e63-3d7d4794c580.png)
[test_1.txt](https://github.com/eamontoyaa/pyCSS/files/810972/test_1.txt)
