### ISSUE TITLE
¿El programa está descontinuado?

### ISSUE THREAD

**Issue by 4lrdyD** [eamontoyaa/pyCSS#4]
Hola, he intentado usar el programa en Ubuntu 20.04 siguiendo el manual adjunto, puedo descargar y ejecutar el programa hasta ver la interfaz, relleno los datos como se muestra a continuación.
![imagen](https://user-images.githubusercontent.com/25991723/182653053-e8c47471-f32d-4704-9f3e-549e974d42c3.png)
Sin embargo, cuando le doy ejecutar análisis no ejecuta y en la linea de comando me muestra la siguiente salida.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "pyCSS.py", line 376, in cssanalysis
    automaticslipcircles(projectName, projectAuthor, projectDate, \
  File "/home/william/Descargas/pyCSS-master/./functions/automaticslipcircles.py", line 221, in automaticslipcircles
    slicesSTRCell = divideslipintoslices(slipArcSTR, \
  File "/home/william/Descargas/pyCSS-master/./functions/divideslipintoslices.py", line 320, in divideslipintoslices
    terrainSlicePlineCordsArray = extractplinefrom2pts\
  File "/home/william/Descargas/pyCSS-master/./functions/extractplinefrom2pts.py", line 82, in extractplinefrom2pts
    yLeftEnd = surfaceDataCell[pointOnePlineIndex]['intercept']\
TypeError: only integer scalar arrays can be converted to a scalar index
```
Ya que se observa que la última actualización del programa fue hace 6 años, entiendo que el programa puede no estar al día con algunas actualizaciones de python3 u otras dependencias. ¿es eso o estoy haciendo algo mal?, agradesco su respuesta.

**Comment by eamontoyaa** [comment]
Saludos @4lrdyD 

Gracias por intentar usar nuestro programa, el cual, como se dio cuenta, lleva ya varios años sin recibir actualizaciones.

Para el momento en que lo publicamos, no teníamos mucha experiencia estructurando paquetes en Python, por lo cual hay muchas cosas que se deberían mejorar para que siga siendo vigente a pesar de no tener actualizaciones recientes.

Junto con @aarizat estuvimos haciendo unas pruebas, y verificamos que el programa debería funcionar si se tienen las siguientes dependencias y versiones instaladas:
- numpy==1.10.4
- matplotlib==1.5.3
- scipy==0.17.1
Las pruebas se realizaron en ambientes virtuales con Python 3.5.10 y 3.6.15.

Esperamos dentro de poco retomar este programa para empaquetarlo adecuadamente para que pueda seguir siendo utilizado.
Si tiene alguna dificultad adicional, hágamela saber para ayudarle a encontrar una solución.

**Comment by 4lrdyD** [comment]
Hola, gracias por contestar, las versiones que tengo son:

- Python ==3.8.10
- numpy ==1.17.4
- matplotlib==3.1.2
- scipy==1.3.3
- tk==3.8.10

Para obtener las versiones escribí:

```
~$ python3 --version
Python 3.8.10
~$ sudo apt-get install python3-numpy
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
python3-numpy ya está en su versión más reciente (1:1.17.4-5ubuntu3).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 26 no actualizados.
~$ sudo apt-get install python3-scipy
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
python3-scipy ya está en su versión más reciente (1.3.3-3build1).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 26 no actualizados.
~$ sudo apt-get install python3-matplotlib
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
python3-matplotlib ya está en su versión más reciente (3.1.2-1ubuntu4).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 26 no actualizados.
~$ sudo apt-get install python3-tk
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
python3-tk ya está en su versión más reciente (3.8.10-0ubuntu1~20.04).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 26 no actualizados.
```
tk es una dependencia según el manual. Las versiones son las más recientes, ¿debería instalar todas las versiones que mencionas, incluido el de python3?, ¿o cuál de esas versiones son estrictamente necesarias?.

**Comment by eamontoyaa** [comment]
@4lrdyD 

Cuando uno instala un paquete y no especifica la versión, el buscador tratará de instalar la versión más reciente por defecto. Es por eso que le salen versiones mucho más actualizadas que las que le indiqué.
En ese sentido, y corrigiendo el mismo manual (que también debe ser actualizado) le sugiero instalar los paquetes con el comando `pip install numpy==1.10.4` y así sucesivamente con las otras dependencias que le especifiqué.

En teoría, `tk` viene con la librería estandar de python, pero si por alguna razón no lo tiene, puede darle `pip install tk` sin especificar versión, ya que se asociaría a la respectiva versión de Python activa.

Sobre la versión de Python, yo en particular hice la prueba en Python 3.5 y 3.6 que eran las versiones existentes para la fecha de creación del programa. No estoy seguro si funcione en 3.8, puedo hacer una prueba cuando pueda sacar un rato, o si ud lo prueba y lo confirma, me lo hace saber por favor.

Sería conveniente que trabajara en un ambiente virtual para que aisle todas estas versiones y no afecte la configuración global que tenga de su Python en su computador. ¿Sabe cómo hacerlo?

Estaré atento.

**Comment by eamontoyaa** [comment]
@4lrdyD 

Cuando uno instala un paquete y no especifica la versión, el buscador tratará de instalar la versión más reciente por defecto. Es por eso que le salen versiones mucho más actualizadas que las que le indiqué.
En ese sentido, y corrigiendo el mismo manual (que también debe ser actualizado) le sugiero instalar los paquetes con el comando `pip install numpy==1.10.4` y así sucesivamente con las otras dependencias que le especifiqué.

En teoría, `tk` viene con la librería estandar de python, pero si por alguna razón no lo tiene, puede darle `pip install tk` sin especificar versión, ya que se asociaría a la respectiva versión de Python activa.

Sobre la versión de Python, yo en particular hice la prueba en Python 3.5 y 3.6 que eran las versiones existentes para la fecha de creación del programa. No estoy seguro si funcione en 3.8, puedo hacer una prueba cuando pueda sacar un rato, o si ud lo prueba y lo confirma, me lo hace saber por favor.

Sería conveniente que trabajara en un ambiente virtual para que aisle todas estas versiones y no afecte la configuración global que tenga de su Python en su computador. ¿Sabe cómo hacerlo?

Estaré atento.

**Comment by 4lrdyD** [comment]
No se como aislar las versiones, sería de mucha ayuda si me ahorraras el trabajo de buscar como hacerlo.

**Comment by 4lrdyD** [comment]
Hola, logré aislar un entorno en donde puedo usar el programa con python 3.6.15 y la versiones de las dependencias recomendadas:
```
$python --version
Python 3.6.15
$ pip list
Package         Version
--------------- -------
cycler          0.11.0
matplotlib      1.5.3
numpy           1.10.4
pip             21.3.1
pyparsing       3.0.9
python-dateutil 2.8.2
pytz            2022.2
scipy           0.17.1
setuptools      59.6.0
six             1.16.0
tk              0.1.0
wheel           0.37.1
```
Y está funcionando perfectamente. La istalación de las versiones no fué sencilla así que intentaré resumir todo el procedimiento:
1. Luego de descargar, descomprimir y construir python3.6.15,  he creado un entorno virtual con `virtualenv` usando:
`$ virtualenv -p /usr/local/bin/python3.6 PyCSS`

2. Activando el entorno virtual, para evitar los errores con TLS/SSL he tenido que usar:

  `sudo apt install libssl-dev libncurses5-dev libsqlite3-dev libreadline-dev libtk8.6 libgdm-dev libdb4o-cil-dev libpcap-dev`

  Luego, ubicándome en la carpeta descomprimida de Python 3.6.15 ejecuté:

 ```
 ./configure
 make
 make install
 ```
 que es el procedimiento para construir nuevamente python3.6.15
 [Fuente aqui.](https://stackoverflow.com/questions/45954528/pip-is-configured-with-locations-that-require-tls-ssl-however-the-ssl-module-in)(Ver respuesta de Rafael Beirigo)

3. Luego ya fué posible la instalación de:
 ```
pip install numpy==1.10.4
pip install matplotlib==1.5.3
```
4. Para la instalación de scipy tuve que hacer:
```
sudo apt-get install libopenblas-dev
pip install scipy==0.17.1
pip install tk
```
5. Aún obtuve un error con el módulo _tkinter que solucioné con `sudo apt-get install tk-dev` y construyendo nuevamente python según se describe en el paso 2.

Siguiendo estos pasos ya pude ejecutar y usar el programa sin problemas. 

Estaré atento a cualquier actualización del programa, saludos.

**Comment by eamontoyaa** [comment]
@4lrdyD,

Excelente noticia que lo haya logrado, espero que el programa sea de utilidad. 

Tan pronto tenga un espacio trataré de avanzar en las siguientes tareas:

1. Crear un corto tutorial para el tema de ambientes (el proceso que ud me describió funciona, pero se puede lograr en menos pasos)
2. Actualizar la compatibilidad con versiones modernas de las dependencias del paquete.
3. Actualizar la documentación y pasarla a inglés.
4. Empaquetar el programa para que pueda ser instalado desde pypi mediante `pip install pycss`.

Le estaré avisando de los avances para que los pueda ir probando si es de su interés.

Saludos,

**Comment by 4lrdyD** [comment]
@eamontoyaa, de todas maneras, estaré atento, gracias por el soporte.

**Comment by eamontoyaa** [comment]
@4lrdyD ,
En estos días @aarizat estuvo trabajando en pyCSS y se organizaron algunas cosas que estaban siendo problemáticas. Ya debería poder correr el programa en versiones de Python 3.6 a 3.10. Por favor lea el [readme ](https://github.com/eamontoyaa/pyCSS#readme) que se actualizó un poco también, y en el cual se incluyeron algunas instrucciones para mayor facilidad de uso.

Saludos,

**Comment by 4lrdyD** [comment]
Funcionando perfectamente con:

Python 3.8.10
matplotlib==3.5.3
numpy==1.23.2
scipy==1.9.0

Saludos!
